### ISSUE TITLE
Some troubles when you apply the theme on Wikipedia

### ISSUE THREAD

**Issue by Badjavii** [druxorey/dracula-for-stylus#2]
you're welcome:)

![{9141D037-13CD-4305-8AF9-3C73417C9398}](https://github.com/user-attachments/assets/b0928e91-463f-4eaa-ac24-d652cbbddfd6)

**Comment by graplo** [comment]
I add this code to css file in stylus extension
  
   ```css
 #firstHeading,
    .mw-first-heading,
    .mw-page-title-main {
    color: var(--color-purple-2);
    }

    .mw-parser-output h2,
    .mw-parser-output h3,
    .mw-parser-output h4 {
    color: var(--color-cyan-2);
    }
    
    .mw-wiki-title,
.mw-logo-wordmark,
.mw-logo-tagline {
    filter: invert(1);
}
```
and work great.
